### ISSUE TITLE
Minor errors reported by cppcheck

### ISSUE THREAD

**Issue by frederic-mahe** [mimitantono/p-swarm#4]
Hi,

The code analyzer `cppcheck` reports two minor errors and a small memory leak in your code:
```
cd p-swarm/
cppcheck --quiet . 
[cluster.cc:170]: (error) Memory leak: iteration_stat
[clusterresult.cc:28]: (error) Uninitialized struct member: info.cluster_members
[main.cc:108]: (error) Uninitialized variable: cluster_data
```
Nothing serious, but you might want to patch that.

**Comment by mimitantono** [comment]
I will look into this. Thank you!

**Comment by mimitantono** [comment]
Fixed the first two problems but it seems that the one in main.cc is a wrong report from cppcheck. 
Ran the check on another computer and it didn't give the error, so I will be closing this issue.
